//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace c_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverCars
    {
        public long IDDriverCars { get; set; }
        public Nullable<long> IDCar { get; set; }
        public Nullable<long> IDDriver { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Drivers Drivers { get; set; }
    }
}
